filter:
  paths: [ "src/*" ]
  excluded_paths: [ "vendor/*", "tests/*", "resources/*", "public/*" , "docs/*" ]

checks:
  php:
    code_rating: true
    duplication: true

tools:
  external_code_coverage: false

build:
  image: default-bionic
  services:
    mysql: 5.7
  environment:
    php:
      version: 8.1.2
      ini:
        xdebug.mode: coverage
    mysql: 5.7
    node: false
    postgresql: false
    mongodb: false
    elasticsearch: false
    redis: false
    memcached: false
    neo4j: false
    rabbitmq: false
    variables:
      APP_ENV: 'github'
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
  dependencies:
    before:
      - composer self-update
      - composer install --no-interaction --prefer-dist --no-progress
      # Set MySQL timezone to swiss time
      - mysql -uroot -e "SET GLOBAL time_zone = '+01:00';"
      # Increase max connections
      - mysql -uroot -e "SET GLOBAL max_connections = 4096;"
      # Create database
      - mysql -uroot -e 'CREATE DATABASE IF NOT EXISTS slim_example_project_test CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'
  tests:
    before:
      - command: composer test:coverage
        coverage:
          file: 'build/logs/clover.xml'
          format: 'clover'
